name: BTreadmill
options:
  bundleIdPrefix: com.lukasz.btreadmill
  deploymentTarget:
    macOS: "13.0"
  developmentLanguage: en

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: "-"
    ENABLE_HARDENED_RUNTIME: NO
    ENABLE_APP_SANDBOX: NO
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    SWIFT_VERSION: "5.9"

targets:
  BTreadmill:
    type: application
    platform: macOS
    sources:
      - path: BTreadmill
        excludes:
          - "*.md"
    resources:
      - path: BTreadmill/Resources
    settings:
      base:
        INFOPLIST_FILE: BTreadmill/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.lukasz.btreadmill
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "-"
        ENABLE_HARDENED_RUNTIME: NO
        ENABLE_APP_SANDBOX: NO
        LSUIElement: YES  # Run as menu bar app without dock icon
        NSBluetoothAlwaysUsageDescription: "BTreadmill needs Bluetooth access to connect and control your treadmill."
        NSBluetoothPeripheralUsageDescription: "BTreadmill needs Bluetooth access to connect and control your treadmill."
    dependencies:
      - sdk: CoreBluetooth.framework
      - sdk: CoreData.framework
      - sdk: Charts.framework
